title: Carlligraphy
description: Detailing Typography in the World of 4 Wheels
footer_text: Photo by Amir Hosseini on Unsplash
header_feature_image: ../uploads/amir-hosseini-hppvgc3d0w0-unsplash.jpg
header_text: Detailing Typography in the World of 4 Wheels!
header_text_color: "#ffffff"
bannerheight: 100vh
navbarheight: 85px
logo: ../uploads/screenshot-276-.png
favicon: ../uploads/screenshot-276-.png
gridlayout: false
fixednavbar: true
upzoom: true
