title: Carlligraphy
description: Detailing the Typography in the World of 4 Wheels
footer_text: Copyright 2021 Your name
header_feature_image: ../uploads/joshua-koblin-eqw1mpinev4-unsplash.jpg
header_text: Detailing the Typography in the World of 4 Wheels!
header_text_color: "#000000"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
